In [4]:
from conexao import buscar_dados
import pandas as pd

dados = buscar_dados()

df = pd.DataFrame(dados)

len(df)

200

200

In [5]:
df.columns

Index(['id', 'name', 'brewery_type', 'address_1', 'address_2', 'address_3',
       'city', 'state_province', 'postal_code', 'country', 'longitude',
       'latitude', 'phone', 'website_url', 'state', 'street'],
      dtype='str')

In [6]:
df = df[['name','state', 'brewery_type','website_url']]

In [7]:
df.head()

,name,state,brewery_type,website_url
0,(405) Brewing Co,Oklahoma,micro,http://www.405brewing.com
1,(512) Brewing Co,Texas,micro,http://www.512brewing.com
2,1 of Us Brewing Company,Wisconsin,micro,https://www.1ofusbrewing.com
3,10 Barrel Brewing Co,Oregon,large,http://www.10barrel.com
4,10 Barrel Brewing Co,Oregon,large,NaN

Definindo os Valores NUlos

In [8]:
df['website_url'] = df['website_url'].fillna('nao informado')
df.head()

,name,state,brewery_type,website_url
0,(405) Brewing Co,Oklahoma,micro,http://www.405brewing.com
1,(512) Brewing Co,Texas,micro,http://www.512brewing.com
2,1 of Us Brewing Company,Wisconsin,micro,https://www.1ofusbrewing.com
3,10 Barrel Brewing Co,Oregon,large,http://www.10barrel.com
4,10 Barrel Brewing Co,Oregon,large,nao informado

In [9]:
df = df.dropna()

In [10]:
df.count()

name            200
state           200
brewery_type    200
website_url     200
dtype: int64

In [11]:
from sqlalchemy import create_engine
import os
from dotenv import  load_dotenv
load_dotenv()


user = os.getenv("POSTGRES_USER")
password = os.getenv("POSTGRES_PASSWORD")
host = os.getenv("postgres_host")
database = os.getenv("POSTGRES_DB")



engine = create_engine(f"postgresql+psycopg2://{user}:{password}@localhost:5432/{database}")



print("USER:", os.getenv("POSTGRES_USER"))
print("PASSWORD:", os.getenv("POSTGRES_PASSWORD"))
print("HOST:", os.getenv("postgres_host"))
print("DB:", os.getenv("POSTGRES_DB"))

USER: vinicius
PASSWORD: 123456789
HOST: None
DB: DataStudy

In [12]:
df.columns = df.columns.str.lower()

df.to_sql(
    name='final',
    con=engine,
    schema='finaldesemana',
    if_exists='append',
    index=False
)

200